import Navbar from "@/components/NavBar";
import { Locale, routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import "./globals.css";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
  subsets: ["latin", "cyrillic"], // Поддержка кириллицы
  variable: "--font-open-sans", // CSS переменная
  weight: ["300", "400", "600", "700"], // Доступные веса
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: Locale };
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = params;

  // Проверяем, поддерживается ли переданный locale
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // Загружаем сообщения для локализации
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${openSans.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          {children}
          {/* <Footer /> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}