import Navbar from "@/components/NavBar";
import { Locale, routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
// import localFont from "next/font/local";
import { notFound } from "next/navigation";
import "./globals.css";
import Footer from "@/components/footer";

import { Lato, Open_Sans, Nanum_Gothic } from "next/font/google";





const lato = Lato({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-lato" });
const openSans = Open_Sans({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-open-sans" });
const nanumGothic = Nanum_Gothic({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-nanum-gothic" });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <html lang={locale} className={`${lato.variable} ${openSans.variable} ${nanumGothic.variable}`}>
      <body
        className={`${lato.variable} ${openSans.variable} ${nanumGothic.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>

          <Navbar />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
